services:
  app:
    build: .
    container_name: caffeine_backend
    ports:
      - "3000:3000" # Mapea el puerto local 3000 al puerto del contenedor
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/Test1 # URL de conexión a MongoDB
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:8
    container_name: caffeine_db
    ports:
      - "27017:27017" # Exponer el puerto de MongoDB
    volumes:
      - mongodb_data:/data/db # Persistencia de datos

volumes:
  mongodb_data:
